# "forest" scenario

globalMap:
  scenarioName: "forest"
  resolution: 0.1   # [m]
  groundTruthImage: "$(find dmce_sim)/maps/forest.png"


robot:
  diameter: 1 # [m]
  speed: 1    # [m/s]
  map: # Parameters for the robot's local submap
    resolution: 0.5 # [m]
  startingArea:
    position_x: -5 # [m]
    position_y: 2.5 # [m]
